name: Proto
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.17.3"

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-proto-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get Dependencies
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: gen-proto
        run: make gen-proto

      - name: Get changed files
        id: changes
        run: |
          git add -A
          echo "::set-output name=go::$(git status --porcelain | grep .go$ | xargs)"

      - name: echo changed files
        if: ${{ steps.changes.outputs.go }}
        run: |
          echo "Please run `make gen-proto`"
          echo "${{ steps.changes.outputs.go }}"
          git diff --staged
         # exit 1
