name: "CI-registration-publisher"

on: [workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::656854603944:role/utm-ms-dev-github-oidc-role
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          DOCKER_BUILDKIT: 1
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          GIT_ACCESS_KEY: ${{ secrets.GIT_ACCESS_KEY }}
        run: |
          NAMES=( "utm-registration-publisher" )
          PATHS=( "containers/publisher/registration/production/Dockerfile" )
          for i in "${!NAMES[@]}"
          do
            docker build -t $ECR_REGISTRY/${NAMES[$i]}:${IMAGE_TAG} -f ${PATHS[$i]} .
            if  !(docker push $ECR_REGISTRY/${NAMES[$i]}:${IMAGE_TAG})
            then
              echo "Fail to push $ECR_REGISTRY/${NAMES[$i]}:${IMAGE_TAG}"
            fi
          done
          
          # sudo apt-get install -y git
          # git --version
          # git clone https://${GIT_ACCESS_KEY}@github.com/TerraDrone/utm-deployment.git
          # cd utm-deployment
          # for i in "${NAMES[@]}"
          # do           
          #   name=$(echo "$i"|sed "s/utm-//")
          #   if  !(sed -i "s/newTag: .*/newTag: "${IMAGE_TAG}"/g" ./applications/$name/overlays/dev/kustomization.yaml)
          #   then
          #     echo "Fail to edit $i"
          #   fi
          # done
          # git config user.name "github-ci"
          # git config user.email "github-ci@terra-drone.co.jp"
          # git add .
          # git commit -m "Upgraded with the tag ${IMAGE_TAG}"
          # git push
